### ISSUE TITLE
Unstable signal?

### ISSUE THREAD

**Issue by stijnb1234** [andyboeh/esphome-dmx512#15]
I'm using your component with my ESP32 Wrover kit. I've connected two different lights to it, but one of the lights is flashing every second for a short period. What can cause this?

I've connected the ESP32 to a MAX485 module as described in your README.

My ESPHome configuration:
```yml
external_components:
  - source: github://andyboeh/esphome-dmx512

esphome:
  name: esp-rgbdmx
  platform: esp32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "esp-p1reader"
    password: !secret fallback_password

captive_portal:

logger:
  baud_rate: 0

api:

ota:
  password: !secret ota_password

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: GPIO1
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  tx_pin: GPIO1
  uart_num: 0

output:
  - platform: dmx512
    channel: 2
    universe: dmx
    id: lskon_red
  - platform: dmx512
    channel: 1
    universe: dmx
    id: lskon_green
  - platform: dmx512
    channel: 3
    universe: dmx
    id: lskon_blue
  - platform: dmx512
    channel: 4
    universe: dmx
    id: lskon_white
    
  - platform: dmx512
    channel: 5
    universe: dmx
    id: tdcsrig_master
  - platform: dmx512
    channel: 6
    universe: dmx
    id: tdcsrig_redyellow
  - platform: dmx512
    channel: 7
    universe: dmx
    id: tdcsrig_greenwhite
  - platform: dmx512
    channel: 8
    universe: dmx
    id: tdcsrig_bluepink
  - platform: dmx512
    channel: 9
    universe: dmx
    id: tdcsrig_strobe
  - platform: dmx512
    channel: 10
    universe: dmx
    id: tdcsrig_motor
  - platform: dmx512
    channel: 11
    universe: dmx
    id: tdcsrig_macro

light:
  - platform: rgbw
    name: LedstripKoning RGBW
    id: lskon_rgbw
    red: lskon_red
    green: lskon_green
    blue: lskon_blue
    white: lskon_white
    icon: mdi:spotlight
    default_transition_length: 0.3s
    color_interlock: false
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_ON
  - platform: monochromatic
    name: Ayra TDC Sunrise Right
    output: tdcsrig_master
    icon: mdi:blur
    disabled_by_default: true
    default_transition_length: 2s
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_ON
  - platform: rgb
    name: Ayra TDC Sunrise Right RGB
    id: tdcsrig
    red: tdcsrig_redyellow
    green: tdcsrig_greenwhite
    blue: tdcsrig_bluepink
    icon: mdi:spotlight
    default_transition_length: 0.3s
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_ON
```
