### ISSUE TITLE
E131 input to DMX output

### ISSUE THREAD

**Issue by filmgarage** [andyboeh/esphome-dmx512#22]
This issue is somehow related to this component.

I am trying to create an ESPhome node to receive E131 commands from jinx or some other source to control a light and to spit out these settings to a DMX output with the esphome-dmx512 component through a 485 module. Outputting the DMX signal is working fine but I can't get the E131 traffic from my source to control the same light. It would be great to have this light function with the E131 input and DMX output while having ESPhome/HA as a "man in the middle". Is anyone capable of adding the missing link here?

```yaml
e131:
  method: multicast

output:
  - platform: dmx512
    channel: 1
    universe: dmx
    id: dmx_ch1

light:
  - platform: monochromatic
    name: "DMX from SACN"
    output: dmx_ch1
    id: sacn2dmx_light
    gamma_correct: 0
  - platform: partition
    id: test_light
    segments:
     - single_light_id: sacn2dmx_light
    effects:
      - e131:
          universe: 1
          channels: MONO

uart:
  id: uart_bus
  tx_pin: GPIO2
  rx_pin: GPIO3
  baud_rate: 9600

dmx512:
  id: dmx
  uart_id: uart_bus
  # enable_pin: GPIO33 # optional
  tx_pin: GPIO2
  uart_num: 1
  periodic_update: true # optional
  force_full_frames: false #optional
  custom_break_len: 92 #optional
  custom_mab_len: 12 #optional
  update_interval: 500 #optional
```
