### ISSUE TITLE
possibility to improve reaction time ?

### ISSUE THREAD

**Issue by koraysels** [andyboeh/esphome-dmx512#23]
Hi, 
I made this work wiht an esp32 d1 mini and a generic max512 modbus board. It intergrates perfectly in home assistant and works as it should, But the delay is very noticable. like 1 second to turn on or off. 
Does that ahve to do with wifi speed or the serial library?  can this possibly be improved ?

thanks a bunch!

**Comment by koraysels** [comment]
So this is my config

```
esphome:
  name: dmxboard

external_components:
  - source: github://andyboeh/esphome-dmx512


esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: <red>

ota:
  password: <red>

wifi:
  ssid: <red>
  password: <red>
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dmxboard Fallback Hotspot"
    password: <red>

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: GPIO5
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: GPIO33
  periodic_update: true # optional
  tx_pin: GPIO5
  update_interval: 100
  uart_num: 1

output:
  - platform: dmx512
    channel: 1
    universe: dmx
    id: dmx_1
  - platform: dmx512
    channel: 2
    universe: dmx
    id: dmx_2
  - platform: dmx512
    channel: 3
    universe: dmx
    id: dmx_3

light:
  - platform: monochromatic
    name: "DMX channel 1"
    output: dmx_1
    id: light_ch1
    default_transition_length: 0.5s
  - platform: monochromatic
    name: "DMX channel 2"
    output: dmx_2
    id: light_ch2
    default_transition_length: 0.5s
  - platform: monochromatic
    name: "DMX channel 3"
    output: dmx_3
    id: light_ch3
    default_transition_length: 0.5s

captive_portal:
    
```


Now that i set the defailt transition length to 0.5s it responds faster. I think the lamp I was using (a cheap ikea dimmable LED light bulb) has a werid response curve where it only tunrs on at 30% so it appears like a slow reacton time. If I set the transition to 0 it is near instant on. So my ba, thanks for looking in to it! And thanks for this library!
