### ISSUE TITLE
Esphome version 12.0 enforces pins unique usage

### ISSUE THREAD

**Issue by jul-fls** [andyboeh/esphome-dmx512#30]
Hello,
In new version of esphome (12.0), a new security feature has been introduced called "Pin Reuse Validation" [Pin Reuse Validation Documentation](https://esphome.io/changelog/2023.12.0.html#pin-reuse-validation)  that prevents a pin from being used in 2 different locations. There is a bypass available [here](https://esphome.io/guides/configuration-types#pin-schema) called "allow_other_uses" that can be set to "true" under a "pin" entry, so I had to change my configuration like that to be able to compile the configuration again.
```yaml
uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: 
    number: GPIO2
    allow_other_uses: true # <== add bypass here
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: 
    number: GPIO13
    allow_other_uses: true # <== add bypass here (because i've created a switch to be able to mute the dmx output
  force_full_frames: false
  tx_pin: 
    number: GPIO2
    allow_other_uses: true # <== add bypass here
  uart_num: 1
```

and with this part of the configuration edited it works very well, no problem whatsoever.
If you want, i can create a pull request to edit the examples of the repo, let me know.
Best regards.
