### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by DonBosserez** [andyboeh/esphome-dmx512#35]
I'm trying to install dmx onto an ESP32 WROOM but it looks like the compiler is not liking the uart_number.
Any idea how I can get this to work? 

Yaml:

```
substitutions:
  device_name: "Boiler DMX Controller"

captive_portal:

external_components:
  - source: github://andyboeh/esphome-dmx512

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin:
    number: GPIO17
    allow_other_uses: true
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  periodic_update: true
  tx_pin: 
    number: GPIO17
    allow_other_uses: true
  uart_num: 2

sensor:
  - platform: uptime
    name: ${device_name} Uptime

  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 60s   

output:
  - platform: dmx512
    channel: 1  
    universe: dmx
    id: dmx_1

light:
  - platform: monochromatic
    name: "${device_name} Dimmer"
    output: dmx_1
    id: dimmer_01
    default_transition_length: 1s
    gamma_correct: 0
```

From logs:

`Compiling .pioenvs/dmx-boiler/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
src/esphome/components/dmx512/dmx512esp32idf.cpp: In member function 'virtual void esphome::dmx512::DMX512ESP32IDF::send_break()':
src/esphome/components/dmx512/dmx512esp32idf.cpp:13:31: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
   13 |   uart_set_line_inverse(this->uart_idx_, UART_SIGNAL_TXD_INV);
      |                         ~~~~~~^~~~~~~~~
      |                               |
      |                               int
In file included from src/esphome/components/dmx512/dmx512esp32idf.cpp:5:
/data/cache/platformio/packages/framework-espidf/components/esp_driver_uart/include/driver/uart.h:262:45: note:   initializing argument 1 of 'esp_err_t uart_set_line_inverse(uart_port_t, uint32_t)'
  262 | esp_err_t uart_set_line_inverse(uart_port_t uart_num, uint32_t inverse_mask);
      |                                 ~~~~~~~~~~~~^~~~~~~~
src/esphome/components/dmx512/dmx512esp32idf.cpp:15:31: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
   15 |   uart_set_line_inverse(this->uart_idx_, UART_SIGNAL_INV_DISABLE);
      |                         ~~~~~~^~~~~~~~~
      |                               |
      |                               int
/data/cache/platformio/packages/framework-espidf/components/esp_driver_uart/include/driver/uart.h:262:45: note:   initializing argument 1 of 'esp_err_t uart_set_line_inverse(uart_port_t, uint32_t)'
  262 | esp_err_t uart_set_line_inverse(uart_port_t uart_num, uint32_t inverse_mask);
      |                                 ~~~~~~~~~~~~^~~~~~~~
*** [.pioenvs/dmx-boiler/src/esphome/components/dmx512/dmx512esp32idf.cpp.o] Error 1
========================== [FAILED] Took 4.72 seconds ==========================`
